/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.SP.frame;

import com.SP.db.dbConn;
import com.SP.panel.ViewPanel;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import java.sql.Statement;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Arvy
 */
public class Admin extends javax.swing.JFrame {

    /**
     * Creates new form Admin
     */
    public Admin() {
        initComponents();
        db.Connect();
        retrieveData();
    }
    
    dbConn db = new dbConn();
    
    public void addStaff() {
    try {
        // Get input data
        String fullname = name1.getText();
        String role1 = role.getText();  // Assume this is where the role is entered by the user
        
        // Check if the role exists
        String checkRoleQuery = "SELECT role_id FROM roleTbl WHERE role_set = ?";
        db.pst = db.con.prepareStatement(checkRoleQuery);
        db.pst.setString(1, role1);
        db.rs = db.pst.executeQuery();
        
        int roleId = -1;
        
        if (db.rs.next()) {
            roleId = db.rs.getInt("role_id");
        } else {
            // Insert the new role if it doesn't exist
            String insertRoleQuery = "INSERT INTO roleTbl (role_set) VALUES (?)";
            db.pst = db.con.prepareStatement(insertRoleQuery, Statement.RETURN_GENERATED_KEYS);
            db.pst.setString(1, role1);
            int rowsAffected = db.pst.executeUpdate();
            
            if (rowsAffected > 0) {
                db.rs = db.pst.getGeneratedKeys();
                if (db.rs.next()) {
                    roleId = db.rs.getInt(1);
                }
            }
        }

        // Insert staff into Staff table
        if (roleId != -1) {
            String insertStaffQuery = "INSERT INTO Staff (fullname, role_ID) VALUES (?, ?)";
            db.pst = db.con.prepareStatement(insertStaffQuery);
            db.pst.setString(1, fullname);
            db.pst.setInt(2, roleId);

            int rowsAffected = db.pst.executeUpdate();

            if (rowsAffected == 1) {
                JOptionPane.showMessageDialog(this, "Staff record added successfully.");
                name1.setText("");
                role.setText("");

            } else {
                JOptionPane.showMessageDialog(this, "Failed to add staff.");
            }
        } else {
            JOptionPane.showMessageDialog(this, "Failed to get role ID.");
        }
    } catch (SQLException ex) {
        JOptionPane.showMessageDialog(this, "Error adding staff: " + ex.getMessage());
    }
}
    
            public void retrieveData() {
        try {
            int q;
            db.pst = db.con.prepareStatement("SELECT s.id, s.fullname, r.role_set AS role, s.password, s.username\n" +
                                             "FROM Staff s\n" + "JOIN roleTbl r ON s.role_id = r.role_id;");
            db.rs = db.pst.executeQuery();
            java.sql.ResultSetMetaData rss = db.rs.getMetaData();
            q = rss.getColumnCount();  

            DefaultTableModel df = (DefaultTableModel) jTable1.getModel();
            df.setRowCount(0);

            while (db.rs.next()) {
                Vector v2 = new Vector();
                for (int a = 1; a  <= q ; a++) {
                    v2.add(db.rs.getString("fullname"));
                    v2.add(db.rs.getString("role"));
                    v2.add(db.rs.getString("password"));
                    v2.add(db.rs.getString("username"));
                    v2.add(db.rs.getInt("id"));
                }
                df.addRow(v2);
            }
            jTable1.getColumnModel().getColumn(4).setMaxWidth(0);
            jTable1.getColumnModel().getColumn(4).setMinWidth(0);
            jTable1.getColumnModel().getColumn(4).setPreferredWidth(0);

        } catch (SQLException ex) {
            Logger.getLogger(ViewPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        add = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        logout = new javax.swing.JLabel();
        role = new javax.swing.JTextField();
        name1 = new javax.swing.JTextField();
        admin1 = new javax.swing.JLabel();
        delete1 = new javax.swing.JLabel();
        update1 = new javax.swing.JLabel();
        BG = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1920, 1080));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        add.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        add.setForeground(new java.awt.Color(255, 255, 255));
        add.setText("ADD");
        add.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addMouseClicked(evt);
            }
        });
        getContentPane().add(add, new org.netbeans.lib.awtextra.AbsoluteConstraints(1710, 520, -1, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Full Name", "Role", "Password", "Username", "ID"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(4).setResizable(false);
        }

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, 950, 830));

        logout.setFont(new java.awt.Font("Dialog", 1, 30)); // NOI18N
        logout.setForeground(new java.awt.Color(255, 255, 255));
        logout.setText("LOGOUT");
        logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutMouseClicked(evt);
            }
        });
        getContentPane().add(logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(1697, 30, 170, 60));

        role.setBackground(new java.awt.Color(255, 255, 255));
        role.setFont(new java.awt.Font("Dialog", 1, 40)); // NOI18N
        role.setForeground(new java.awt.Color(0, 0, 0));
        role.setToolTipText("");
        role.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                roleActionPerformed(evt);
            }
        });
        getContentPane().add(role, new org.netbeans.lib.awtextra.AbsoluteConstraints(1360, 360, 430, 50));

        name1.setBackground(new java.awt.Color(255, 255, 255));
        name1.setFont(new java.awt.Font("Dialog", 1, 40)); // NOI18N
        name1.setForeground(new java.awt.Color(0, 0, 0));
        name1.setToolTipText("");
        name1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                name1ActionPerformed(evt);
            }
        });
        getContentPane().add(name1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1360, 280, 430, 40));

        admin1.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        admin1.setForeground(new java.awt.Color(255, 255, 255));
        admin1.setText("ADMIN");
        getContentPane().add(admin1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 40, -1, -1));

        delete1.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        delete1.setForeground(new java.awt.Color(255, 255, 255));
        delete1.setText("DELETE");
        delete1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                delete1MouseClicked(evt);
            }
        });
        getContentPane().add(delete1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1180, 520, -1, -1));

        update1.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        update1.setForeground(new java.awt.Color(255, 255, 255));
        update1.setText("UPDATE");
        update1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                update1MouseClicked(evt);
            }
        });
        getContentPane().add(update1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1430, 520, -1, -1));

        BG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/SP/img/Admin_1.png"))); // NOI18N
        getContentPane().add(BG, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void logoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutMouseClicked
      login loginFrame = new login();
      loginFrame.setVisible(true);
      this.dispose();
    }//GEN-LAST:event_logoutMouseClicked

    private void roleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_roleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_roleActionPerformed

    private void name1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_name1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_name1ActionPerformed

    private void delete1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_delete1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_delete1MouseClicked

    private void update1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_update1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_update1MouseClicked

    private void addMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_addMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Admin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BG;
    private javax.swing.JLabel add;
    private javax.swing.JLabel admin1;
    private javax.swing.JLabel delete1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel logout;
    private javax.swing.JTextField name1;
    private javax.swing.JTextField role;
    private javax.swing.JLabel update1;
    // End of variables declaration//GEN-END:variables
}
