
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.SP.frame;


import com.SP.panel.*;

/**
 *
 * @author Arvy
 */
public class Staff_dashboard extends javax.swing.JFrame {

    /**
     * Creates new form Staff_dashboard
     */
    public Staff_dashboard() {
        initComponents();
        onStrt();
    }
    
    public void onStrt(){
        addProduct1.setVisible(false);
        updateProduct1.setVisible(false);
        viewPanel1.setVisible(true);
    }
    
    public void addPrd(){
        viewPanel1.setVisible(false);
        updateProduct1.setVisible(false);
        addProduct1.setVisible(true);
    }
    
    public void udPrd(){
        viewPanel1.setVisible(false);
        addProduct1.setVisible(false);
        updateProduct1.setVisible(true);
    }
  
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        logout = new javax.swing.JLabel();
        dashboard = new javax.swing.JLabel();
        add = new javax.swing.JLabel();
        update = new javax.swing.JLabel();
        delete1 = new javax.swing.JLabel();
        viewPanel1 = new com.SP.panel.ViewPanel();
        updateProduct1 = new com.SP.panel.UpdateProduct();
        addProduct1 = new com.SP.panel.AddProduct();
        BG = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        logout.setFont(new java.awt.Font("Dialog", 1, 30)); // NOI18N
        logout.setForeground(new java.awt.Color(255, 255, 255));
        logout.setText("LOGOUT");
        logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutMouseClicked(evt);
            }
        });
        getContentPane().add(logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(1750, 30, -1, -1));

        dashboard.setFont(new java.awt.Font("Dialog", 1, 30)); // NOI18N
        dashboard.setForeground(new java.awt.Color(255, 255, 255));
        dashboard.setText("DASH BOARD");
        dashboard.setToolTipText("");
        dashboard.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dashboardMouseClicked(evt);
            }
        });
        getContentPane().add(dashboard, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, -1, -1));

        add.setFont(new java.awt.Font("Dialog", 1, 30)); // NOI18N
        add.setForeground(new java.awt.Color(255, 255, 255));
        add.setText("ADD");
        add.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addMouseClicked(evt);
            }
        });
        getContentPane().add(add, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 10, -1, -1));

        update.setFont(new java.awt.Font("Dialog", 1, 30)); // NOI18N
        update.setForeground(new java.awt.Color(255, 255, 255));
        update.setText("UPDATE");
        update.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                updateMouseClicked(evt);
            }
        });
        getContentPane().add(update, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 10, -1, -1));

        delete1.setFont(new java.awt.Font("Dialog", 1, 30)); // NOI18N
        delete1.setForeground(new java.awt.Color(255, 255, 255));
        delete1.setText("DELETE");
        delete1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                delete1MouseClicked(evt);
            }
        });
        getContentPane().add(delete1, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 10, -1, -1));
        getContentPane().add(viewPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, -1, -1));
        getContentPane().add(updateProduct1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, -1, -1));
        getContentPane().add(addProduct1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, -1, -1));

        BG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/SP/img/STAFF_DASHBOARD_1.png"))); // NOI18N
        getContentPane().add(BG, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void dashboardMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dashboardMouseClicked
        onStrt();
    }//GEN-LAST:event_dashboardMouseClicked

    private void addMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addMouseClicked
        addPrd();
    }//GEN-LAST:event_addMouseClicked

    private void updateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updateMouseClicked
        udPrd();
    }//GEN-LAST:event_updateMouseClicked

    private void logoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutMouseClicked
      login loginFrame = new login();
      loginFrame.setVisible(true);
      this.dispose();
    }//GEN-LAST:event_logoutMouseClicked

    private void delete1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_delete1MouseClicked
        // TODO add your handling code here:
        onStrt();
    }//GEN-LAST:event_delete1MouseClicked

   
    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BG;
    private javax.swing.JLabel add;
    private com.SP.panel.AddProduct addProduct1;
    private javax.swing.JLabel dashboard;
    private javax.swing.JLabel delete1;
    private javax.swing.JLabel logout;
    private javax.swing.JLabel update;
    private com.SP.panel.UpdateProduct updateProduct1;
    private com.SP.panel.ViewPanel viewPanel1;
    // End of variables declaration//GEN-END:variables
}
