/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.SP.panel;

/**
 *
 * @author Arvy
 */
public class AddProduct extends javax.swing.JPanel {

    /**
     * Creates new form AddProduct
     */
    public AddProduct() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        brand1 = new javax.swing.JTextField();
        category1 = new javax.swing.JTextField();
        model = new javax.swing.JTextField();
        price = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        add = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(1920, 970));
        setMinimumSize(new java.awt.Dimension(1920, 970));
        setPreferredSize(new java.awt.Dimension(1920, 970));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        brand1.setEditable(false);
        brand1.setBackground(new java.awt.Color(255, 255, 255));
        brand1.setFont(new java.awt.Font("Dialog", 1, 40)); // NOI18N
        brand1.setForeground(new java.awt.Color(0, 0, 0));
        brand1.setText("Acer");
        brand1.setToolTipText("");
        add(brand1, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 230, 680, 90));

        category1.setEditable(false);
        category1.setBackground(new java.awt.Color(255, 255, 255));
        category1.setFont(new java.awt.Font("Dialog", 1, 40)); // NOI18N
        category1.setForeground(new java.awt.Color(0, 0, 0));
        category1.setText("Gaming");
        category1.setToolTipText("");
        add(category1, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 370, 680, 90));

        model.setEditable(false);
        model.setBackground(new java.awt.Color(255, 255, 255));
        model.setFont(new java.awt.Font("Dialog", 1, 40)); // NOI18N
        model.setForeground(new java.awt.Color(0, 0, 0));
        model.setText("Nitro 58ye");
        model.setToolTipText("");
        add(model, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 510, 680, 90));

        price.setEditable(false);
        price.setBackground(new java.awt.Color(255, 255, 255));
        price.setFont(new java.awt.Font("Dialog", 1, 40)); // NOI18N
        price.setForeground(new java.awt.Color(0, 0, 0));
        price.setText("48,000");
        price.setToolTipText("");
        price.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                priceActionPerformed(evt);
            }
        });
        add(price, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 650, 680, 80));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/SP/img/Add-panell.png"))); // NOI18N
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 120, -1, -1));

        add.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        add.setForeground(new java.awt.Color(255, 255, 255));
        add.setText("ADD");
        add(add, new org.netbeans.lib.awtextra.AbsoluteConstraints(1180, 820, 170, 90));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/SP/img/addbutton.png"))); // NOI18N
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 820, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void priceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_priceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_priceActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel add;
    private javax.swing.JTextField brand1;
    private javax.swing.JTextField category1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField model;
    private javax.swing.JTextField price;
    // End of variables declaration//GEN-END:variables
}
