/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.SP.panel;

import com.SP.db.dbConn;
import java.sql.SQLException;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Arvy
 */
public class UpdateProduct extends javax.swing.JPanel {

    /**
     * Creates new form UpdateProduct
     */
    public UpdateProduct() {
        initComponents();
        db.Connect();
        retrieveData();
    }
    
    dbConn db = new dbConn();
    
            public void retrieveData() {
        try {
            int q;
            db.pst = db.con.prepareStatement("SELECT * FROM product");
            db.rs = db.pst.executeQuery();
            java.sql.ResultSetMetaData rss = db.rs.getMetaData();
            q = rss.getColumnCount();  

            DefaultTableModel df = (DefaultTableModel) jTable1.getModel();
            df.setRowCount(0);

            while (db.rs.next()) {
                Vector v2 = new Vector();
                for (int a = 1; a  <= q ; a++) {
                    v2.add(db.rs.getString("CATEGORY"));
                    v2.add(db.rs.getString("BRAND_ID"));
                    v2.add(db.rs.getString("MODEL"));
                    v2.add(db.rs.getString("QUANTITY"));
                    v2.add(db.rs.getString("PRICE"));
                    v2.add(db.rs.getInt("p_id"));
                }
                df.addRow(v2);
            }
            jTable1.getColumnModel().getColumn(5).setMaxWidth(0);
            jTable1.getColumnModel().getColumn(5).setMinWidth(0);
            jTable1.getColumnModel().getColumn(5).setPreferredWidth(0);

        } catch (SQLException ex) {
            Logger.getLogger(ViewPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
           
            
    public void search() {
        // Make sure a row is selected
        int selectedRow = jTable1.getSelectedRow();
        if (selectedRow == -1) {
            return;  // If no row is selected, return and do nothing
        }

        DefaultTableModel tbModel = (DefaultTableModel) jTable1.getModel();

        // Get values from the selected row
        String brand = tbModel.getValueAt(selectedRow, 0).toString();  // Assuming brand is in the first column
        String cat = tbModel.getValueAt(selectedRow, 1).toString();    // Category in the second column
        String model = tbModel.getValueAt(selectedRow, 2).toString();  // Model in the third column
        String qty = tbModel.getValueAt(selectedRow, 3).toString();    // Quantity in the fourth column
        String price = tbModel.getValueAt(selectedRow, 4).toString();  // Price in the fifth column

        // Update the text fields with the selected row's data
        brand1.setText(brand);
        category.setText(cat);
        model1.setText(model);
        quantity.setText(qty);
        price1.setText(price);
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        brand1 = new javax.swing.JTextField();
        category = new javax.swing.JTextField();
        model1 = new javax.swing.JTextField();
        quantity = new javax.swing.JTextField();
        update = new javax.swing.JLabel();
        butup = new javax.swing.JLabel();
        price1 = new javax.swing.JTextField();
        panellin = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(1920, 970));
        setMinimumSize(new java.awt.Dimension(1920, 970));
        setPreferredSize(new java.awt.Dimension(1920, 970));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Category", "Brand", "Model", "Quantity", "Price", "ID"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setResizable(false);
            jTable1.getColumnModel().getColumn(1).setResizable(false);
            jTable1.getColumnModel().getColumn(3).setResizable(false);
            jTable1.getColumnModel().getColumn(4).setResizable(false);
            jTable1.getColumnModel().getColumn(5).setResizable(false);
        }

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 1000, 920));

        brand1.setEditable(false);
        brand1.setBackground(new java.awt.Color(255, 255, 255));
        brand1.setFont(new java.awt.Font("Dialog", 1, 40)); // NOI18N
        brand1.setForeground(new java.awt.Color(0, 0, 0));
        brand1.setToolTipText("");
        add(brand1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1310, 80, 520, 50));

        category.setEditable(false);
        category.setBackground(new java.awt.Color(255, 255, 255));
        category.setFont(new java.awt.Font("Dialog", 1, 40)); // NOI18N
        category.setForeground(new java.awt.Color(0, 0, 0));
        category.setToolTipText("");
        category.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                categoryActionPerformed(evt);
            }
        });
        add(category, new org.netbeans.lib.awtextra.AbsoluteConstraints(1310, 200, 520, 50));

        model1.setEditable(false);
        model1.setBackground(new java.awt.Color(255, 255, 255));
        model1.setFont(new java.awt.Font("Dialog", 1, 40)); // NOI18N
        model1.setForeground(new java.awt.Color(0, 0, 0));
        model1.setToolTipText("");
        model1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                model1ActionPerformed(evt);
            }
        });
        add(model1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1310, 310, 520, 50));

        quantity.setEditable(false);
        quantity.setBackground(new java.awt.Color(255, 255, 255));
        quantity.setFont(new java.awt.Font("Dialog", 1, 40)); // NOI18N
        quantity.setForeground(new java.awt.Color(0, 0, 0));
        quantity.setToolTipText("");
        quantity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quantityActionPerformed(evt);
            }
        });
        add(quantity, new org.netbeans.lib.awtextra.AbsoluteConstraints(1310, 540, 520, 60));

        update.setFont(new java.awt.Font("Dialog", 1, 30)); // NOI18N
        update.setForeground(new java.awt.Color(255, 255, 255));
        update.setText("UPDATE");
        add(update, new org.netbeans.lib.awtextra.AbsoluteConstraints(1650, 720, -1, -1));

        butup.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/SP/img/updatebutton.png"))); // NOI18N
        add(butup, new org.netbeans.lib.awtextra.AbsoluteConstraints(1590, 690, -1, -1));

        price1.setEditable(false);
        price1.setBackground(new java.awt.Color(255, 255, 255));
        price1.setFont(new java.awt.Font("Dialog", 1, 40)); // NOI18N
        price1.setForeground(new java.awt.Color(0, 0, 0));
        price1.setToolTipText("");
        price1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                price1ActionPerformed(evt);
            }
        });
        add(price1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1310, 420, 520, 60));

        panellin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/SP/img/addpanell.png"))); // NOI18N
        add(panellin, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 10, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void categoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_categoryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_categoryActionPerformed

    private void model1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_model1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_model1ActionPerformed

    private void quantityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quantityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_quantityActionPerformed

    private void price1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_price1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_price1ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        search();
    }//GEN-LAST:event_jTable1MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField brand1;
    private javax.swing.JLabel butup;
    private javax.swing.JTextField category;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField model1;
    private javax.swing.JLabel panellin;
    private javax.swing.JTextField price1;
    private javax.swing.JTextField quantity;
    private javax.swing.JLabel update;
    // End of variables declaration//GEN-END:variables
}
